# Be a champion for open science {#champion} 

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(htmltools)
```

*in development...*

## Objectives and Resources

To provide resources for you to promote good practices for open and reproducible science in your communities and institutions.

## Three messages

If there are 3 things to communicate to others after this workshop, I think they would be: 

**1. Data science is a discipline that can improve your analyses**

- There are concepts, theory, and tools for thinking about and working with data. 
- Your study system is not unique when it comes to data, and accepting this will speed up your analyses.

*This helps your science:*

- Think deliberately about data: when you distinguish data questions from research questions, you'll learn how and who to ask for help
- Save heartache: you don’t have to reinvent the wheel
- Save time: when you expect there’s a better way to do what you are doing, you'll find the solution faster. Focus on the science.


**2. Open data science tools exist**

- Data science tools that enable open science are game-changing for analysis, collaboration and communication.
- Open science is "the concept of transparency at all stages of the research process, coupled with free and open access to data, code, and papers" ([Hampton et al. 2015](http://onlinelibrary.wiley.com/doi/10.1890/ES14-00402.1/abstract)))  

*This helps your science:*

- Have confidence in your analyses from this traceable, reusable record
- Save time through automation, thinking ahead of your immediate task, reduced bookkeeping, and collaboration
- Take advantage of convenient access: working openly online is like having an extended memory

**3. Learn these tools with collaborators and community (redefined):** 

- Your most important collaborator is Future You. 
- Community shoula also be beyond the colleagues in your field.
- Learn from, with, and for others. 

*This helps your science:* 

- If you learn to talk about your data, you'll find solutions faster. 
- Build confidence: these skills are transferable beyond your science.
- Be empathic and inclusive and build a network of allies 

## Build community

Join existing communities locally and online, and start local chapters with friends!

Some ideas: 

- [Mozilla Study Groups](https://science.mozilla.org/programs/studygroups) Example: [Eco-data-science](http://eco-data-science.github.io/). Also see ([Steven et al 2018](https://www.biorxiv.org/content/early/2018/02/15/265421)) 
- [RLadies](https://rladies.org/). Example: [RLadies Santa Barbara](https://www.meetup.com/rladies-santa-barbara/)

These meetups can be for skill-sharing, showcasing how people work, or building community so you can troubleshoot together. They can be an informal "hacky hour" at a cafe or pub!

<!---
## Other lessons

### Naming files

Now is a good interlude to talk about naming things. 

We are going to take five minutes to talk through [Jenny Bryan's three principles for naming files](https://speakerdeck.com/jennybc/how-to-name-files):

1. machine readable
1. human readable
1. play well with default ordering
--->
