# Collaborate with GitHub {#collaborating}

## Overview

The collaborative power of GitHub and RStudio is really game changing. So far we've been collaborating with our most important collaborator: ourselves. But, we are lucky that in science we have so many other collaborators, so let's learn how to use GitHub with one of them. 

We are going to teach you the simplest way to collaborate with someone, which is for both of you to have administration privileges. GitHub is built for software developer teams, and there is a lot of features that we as scientists won't use immediately. 

We will do this all with a partner, and you'll work pretty independently, with us providing help as you go. 

**Objectives**

- create a new repo and give permission to a collaborator
- open as a new RStudio project!
- collaborate with a partner, explore github.com blame, history
- practice more ggplot2 collab

1. add their neighbor as a collaborator to their repo
1. practice more; make changes to their repo, and to their neighbor's. 

**Resources**


## create gh-pages repo and give someone permission

## clone to a new Rproject

## Rmd analysis together

- Rmd analysis


<!---
### RStudio projects (.Rproj)

Follow the steps for cloning that we did before, but when you get to a critical point, click open in another project

TODO: RStudio project! Yes, you can use these without Git, but you probably never will, so that's why we're learning it together.
--->
