---
title: "ggplot2 training"
output: html_document
---

```{r setup, include=FALSE}

install.packages("tidyverse")
library(tidyverse)
```

#mpg dataset

```{r}

mpg

```


```{r}
ggplot(data = mpg)
```


```{r}
ggplot(data = mpg, aes(x = displ, y = hwy)) +
  geom_point()
```

```{r}
#assign this plot to a variable
car_plot <- ggplot(data = mpg, aes(x = displ, y = hwy))

# build off of car_plot
car_plot +
  geom_point()
```


```{r}
ggplot(data = mpg, aes(x = displ, y = hwy)) +
  geom_point(alpha = 0.4)
```

Coloring points in the plot based on class of car (e.g. sub or compact)
```{r}
ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy, color = class))
```


```{r}
ggplot(data = mpg) +
  geom_point(aes(x = cty, y = hwy, size = class, color = fl))
```

```{r}
ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy), alpha = 0.4, color = "blue")
```


```{r}
ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy, shape = cty))
```

```{r}
ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy, colour = displ < 5))
```


# Faceting


```{r}
ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy, color = class)) +
  facet_wrap(~ manufacturer)
```

#remove the gray background using theme_bw()
```{r}
ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy, color = class)) +
  facet_wrap(~ manufacturer) +
  theme_dark()
```

```{r}
install.packages("ggthemes")
library(ggthemes)

ggplot(data = mpg) +
  geom_point(aes(x = displ, y = hwy, color = class)) +
  facet_wrap(~ manufacturer) +
  theme_excel()
```


# Geoms

```{r}
ggplot(mpg, aes(x = drv, y = hwy)) +
  geom_violin()
```


```{r}
ggplot(data = mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth()
```



```{r}
ggplot(data = mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(color = "red")
```


# Bar Charts

```{r}
ggplot(data = mpg) +
  geom_bar(aes(x = fl, fill = class), position = "dodge") +
  theme_bw() +
  scale_x_discrete(labels = c("CNG", "Diesel", "Ethanol", "Premium", "Regular")) +
  xlab("Fuel Type") +
  ylab("Number of cars") +
  scale_fill_brewer(palette = "Set3")

RColorBrewer::display.brewer.all()
```

#Saving image
```{r}

ggplot(data = mpg) +
  geom_bar(aes(x = fl, fill = class), position = "dodge") +
  theme_bw() +
  scale_x_discrete(labels = c("CNG", "Diesel", "Ethanol", "Premium", "Regular")) +
  xlab("Fuel Type") +
  ylab("Number of cars") +
  scale_fill_brewer(palette = "Blues")

ggsave("my_plot2.pdf", width = 6, height = 6)
```
























