--- 
title: "Introduction to Open Data Science"
author: "The Ocean Health Index Team"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
# output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: ohi-science/data-science-training
description: "This is official open data science training for the Ocean Health Index."
---

# Welcome {#welcome}

This training book will introduce you to open data science so you can work with data in an open, reproducible, and collaborative way. Open data science means that methods, data, and code are available so that others can access, reuse, and build from it without much fuss. Here you will learn a workflow with R, RStudio, Git, and GitHub, as we describe in [Lowndes *et al. 2017, Nature Ecology & Evolution*: Our path to better science in less time using open data science tools](https://www.nature.com/articles/s41559-017-0160).

This is going to be fun, because learning these open data science tools and practices is empowering! This training book is written (and always improving) so you can use it as self-paced learning, or it can be used to teach an in-person workshop where the instructor live-codes. Either way, you should do everything hands-on on your own computer as you learn. 

Before you begin, be sure you are all set up: see the prerequisites in Chapter \@ref(overview). 

Suggested breakdown for a 2-day workshop: 

|time       |      Day 1|      Day 2|
|:----------|----------:|----------:|
|9-10:30    |  [Motivation](#overview), [R & RStudio, Rmarkdown](#rstudio) |  [Data Wrangling: `tidyr`](#tidyr) |
|break      |  | |
|11-12:30   | [GitHub](#github) | [Programming](#programming) |
|lunch      |  ||
|13:30-15:00 |  [Visualization: `ggplot2`](#ggplot2) | [Collaborating with GitHub](#collaborating) |
|break      |  |  |
|15:30-17:00 |  [Data Wrangling: `dplyr`](#dplyr) | Practice, [Be a champion for open data science](#champion) |

----

This book has been used in the following:

[**Open Data Science Training** — 2 day workshop at the University of Queensland, Australia *2019-06-18*](http://ohi-science.org/uq-training/)

[**Software Carpentry** — 2-day workshop at the Woods Hole Oceanographic Institution (WHOI) *2018-10-22*](https://jules32.github.io/2018-10-22-WHOI/overview) 

[**Data integration and team science** — 4 day workshop at NCEAS, California, USA *2018-03-12*](https://nceas.github.io/crescynt-training/data-integration)

[**Data Carpentry** — 2-day workshop at the University of California Merced *2017-08-17*](https://snacktavish.github.io/2017-08-17-Yosemite/overview/) 

[**Software Carpentry** — 2-day workshop at the Monterey Bay Aquarium Research Institute (MBARI) *2017-11-30*](https://jules32.github.io/2017-11-30-MBARI/overview) 

[**Software Carpentry: Reproducible Science with RStudio and GitHub**  —  2-day workshop at Oxford University *2016-07-12*](http://jules32.github.io/2016-07-12-Oxford/overview/)

[**Software Carpentry**  —  2-day workshop at UC Santa Barbara *2016-04-15*](http://remi-daigle.github.io/2016-04-15-UCSB/overview/)


