# Introduction and motivation {#intro}


**In development.** 

This is a 2-day bootcamp for hands-on learning of R, RStudio, Git, and GitHub, and will teach reproducible workflows that can be used in analyses of all kinds, including Ocean Health Index assessments. 

R, RStudio, Git, and GitHub are freely available and open-source, meaning that anyone can download...

This material builds from a lot of materials developed by others. In particular, it pulls from the following resources, which are excellent and highly recommended for further learning and as resources later on: 

- [R for Data Science]
- [STAT 545]
- [Software Carpentry]
- [Happy Git with R]

## Course overview/Practical details

2-day workshop, split into 4 primary topics. Table of morning, afternoon, day 1, day 2. These materials can be used to teach this 2-day bootcamp, or can be used as a self-paced course

We’ll start with data viz, and then will start using GitHub for reproducible workflows on Day 1. Then on day 2 we’ll continue to use GitHub with RStudio as a way to practice as we learn.

## Data science mindset

New but will become increasingly familiar. We’ll start you off with some momentum, like if you were going to learn to ride a bike or ...

## Expect that there is a way to do what you want to do



## Data science is a discipline

It has theories, methods, and tools. 

Tidyverse and Hadley’s graphic

Going to teach you how to think differently, get into some of the theory but in the context of hands-on work.


See also section in toolbox-training

### Error messages are your friend

They help you learn
You're trying something new, you'll get error messages. they are your friends. yes. they are. 

## Asking for help and recognizing useful answers

## Course prerequisites 

R, RStudio, git, GitHub account.
Mindset listed above. 


## Why RStudio?

- airport
- debugging
- packages
- community

## Troubleshooting
- updating R, RStudio (right-click on 'open', replace, etc)

