# R and RStudio through Data Visualization {#viz}

```{r viz ops, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(htmltools)
```

**In development.** 

## Objectives & Resources

#### Objectives

- learn ggplot2 with `mpg` dataframe (important to play with other data than your own, you'll learn something.)
- practice writing a script (maybe call it mpg_viz.R?)
- practice rstudio-github workflow
- use and credit http://r4ds.had.co.nz/data-visualisation.html

Why do we start with data viz? Not only is data viz a big part of analysis, it’s a way to SEE your progress as you learn to code.
"ggplot2 implements the grammar of graphics, a coherent system for describing and building graphs. With ggplot2, you can do more faster by learning one system and applying it in many places." - [R4DS](http://r4ds.had.co.nz/data-visualisation.html)

- Conceptual and building, cheatsheet images

- http://r4ds.had.co.nz/data-visualisation.html
- https://pdfs.semanticscholar.org/d779/6f85dabccd18673f382c100fc06f55e8b501.pdf

#### Resources

Here are some resources that helped make this tutorial: 
- [R for Data Science](http://r4ds.had.co.nz/data-visualisation.html)
- [ggplot2-cheatsheet-2.0.pdf](../cheatsheets/ggplot2-cheatsheet-2.0.pdf)
- [Interactive Plots and Maps - Environmental Informatics](http://ucsb-bren.github.io/env-info/wk06_widgets.html)
- [Graphs with ggplot2 - Cookbook for R](http://www.cookbook-r.com/Graphs/#graphs-with-ggplot2)
- [ggplot2 Essentials - STHDA](http://www.sthda.com/english/wiki/ggplot2-essentials)

D Robinson:
- http://varianceexplained.org/r/why-I-use-ggplot2/; add screenshot of ggplot2 cheatsheet
- http://varianceexplained.org/RData/


## Install our first package: `ggplot2`

<!--- use the `swc-mbari.R script that we created in the previous section, or create a new script --->

## First Steps

## Aesthetic mappings

## push to GitHub

### Your turn

## Common problems

...


### Your turn

## The Layered Grammar of Graphics

## push to GitHub

## end of the day: intro to Markdown (README)?
so they can post a figure on a readme?

## Troubleshooting

